
/* 
This Query has been Tuned by AI-DBA Query Optimizer (v1.7.0.0).
Copyright (C) 2019-2025 AI-DBA Software Inc, all rights reserved.
Date: 4/22/2025 1:07:24 AM UTC
*/
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_SALESORDERDETAIL_PRODUCTID] ON [ADVENTUREWORKS].[SALES].[SALESORDERDETAIL] ([PRODUCTID],[SALESORDERID],[SALESORDERDETAILID]) INCLUDE ([CARRIERTRACKINGNUMBER],[ORDERQTY],[SPECIALOFFERID],[UNITPRICE],[UNITPRICEDISCOUNT],[ROWGUID],[MODIFIEDDATE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
