
/* 
This Query has been Tuned by AI-DBA Query Optimizer (v1.7.0.0).
Copyright (C) 2019-2024 AI-DBA Software Inc, all rights reserved.
Date: 12/12/2024 4:44:36 PM UTC
*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_241212164448 ON [ADVENTUREWORKS].[SALES].[SALESORDERHEADER] ([SALESORDERID],[ORDERDATE],[STATUS]) INCLUDE ([SUBTOTAL]) ;
 END TRY BEGIN CATCH END CATCH;
