
BEGIN TRY 

--CURRENT VALUE: OFF
ALTER DATABASE [AdventureWorks] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[AdventureWorks] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [AdventureWorks] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[AdventureWorks] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: OFF
USE [AdventureWorks];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
PRINT '[AdventureWorks] BATCH_MODE_ON_ROWSTORE is ON.';
--CURRENT VALUE: OFF
USE [AdventureWorks];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = ON;
PRINT '[AdventureWorks] DEFERRED_COMPILATION_TV  is ON.';
--CURRENT VALUE: OFF
USE [AdventureWorks];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[AdventureWorks] INTERLEAVED_EXECUTION_TVF  is ON.';
--CURRENT VALUE: OFF
USE [AdventureWorks];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[AdventureWorks] ROW_MODE_MEMORY_GRANT_FEEDBACK is ON.';
--CURRENT VALUE: OFF
USE [AdventureWorks];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[AdventureWorks] BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [AdventureWorks] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;