FSUTIL BEHAVIOR SET DISABLELASTACCESS 1;
FSUTIL BEHAVIOR SET MEMORYUSAGE 2;
NETWORK INTERFACE DUPLEX CONFIGURATION;
POWER MANAGEMENT CONFIGURATION;
WINDOWS UPDATE CONFIGURATION;
LOCAL POLICY CONFIGURATION;
