
/* 
This query has been optimized by AI-DBA Query Optimizer (v2.4.2).
Copyright (C) 2025 AI-DBA Software Inc, all rights reserved.
Date: November 22,2025 UTC+0

{CHANGES}

*/
BEGIN TRY     CREATE NONCLUSTERED INDEX AIDBA_NCIX_251122012020 ON [ADVENTUREWORKS].[PERSON].[PERSON] ([DEMOGRAPHICS],[ADDITIONALCONTACTINFO],[TITLE],[SUFFIX],[PERSONTYPE]) INCLUDE ([BUSINESSENTITYID]) ;
 END TRY BEGIN CATCH END CATCH;
BEGIN TRY     CREATE  INDEX [IX_AIDBA_1_20251111] ON [ADVENTUREWORKS].[SALES].[SALESORDERDETAIL] ([SALESORDERDETAILID],[SALESORDERID]) INCLUDE ([CARRIERTRACKINGNUMBER],[ORDERQTY],[PRODUCTID],[SPECIALOFFERID],[UNITPRICE],[UNITPRICEDISCOUNT],[ROWGUID],[MODIFIEDDATE]) WITH (DROP_EXISTING=ON );
 END TRY BEGIN CATCH END CATCH;
