

BEGIN TRY 
    DROP INDEX AIDBA_NCIX_251122012020 ON [ADVENTUREWORKS].[PERSON].[PERSON]; 
END TRY 
BEGIN CATCH 
END CATCH;



BEGIN TRY 
    DROP INDEX [IX_AIDBA_1_20251111] ON [ADVENTUREWORKS].[SALES].[SALESORDERDETAIL]; 
END TRY 
BEGIN CATCH 
END CATCH;