
/* 
This Query has been Tuned by AI-DBA Query Optimizer (v1.7.0.0).
Copyright (C) 2019-2024 AI-DBA Software Inc, all rights reserved.
Date: 12/6/2024 12:31:33 AM UTC
*/
BEGIN TRY     CREATE UNIQUE INDEX [IX_AIDBA_PK_SALESORDERHEADER_SALESORDERID] ON [ADVENTUREWORKS].[SALES].[SALESORDERHEADER] ([SALESORDERID],[SALESORDERDETAILID]) INCLUDE ([CARRIERTRACKINGNUMBER],[ORDERQTY],[SPECIALOFFERID],[UNITPRICE],[UNITPRICEDISCOUNT],[ROWGUID],[MODIFIEDDATE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
