
/* 
This Query has been Tuned by AI-DBA Query Optimizer (v1.7.0.0).
Copyright (C) 2019-2024 AI-DBA Software Inc, all rights reserved.
Date: 12/16/2024 4:51:57 PM UTC
*/
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_SALESORDERDETAIL_PRODUCTID] ON [ADVENTUREWORKS].[SALES].[SALESORDERDETAIL] ([PRODUCTID],[SALESORDERID],[SALESORDERDETAILID]) INCLUDE ([CARRIERTRACKINGNUMBER],[ORDERQTY],[SPECIALOFFERID],[UNITPRICE],[UNITPRICEDISCOUNT],[ROWGUID],[MODIFIEDDATE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
