
ALTER DATABASE [tempdb] MODIFY FILE (NAME=N'tempdev',SIZE=508928KB , FILEGROWTH=524288KB)

DBCC DROPCLEANBUFFERS;
DBCC FREEPROCCACHE;
DBCC FREESESSIONCACHE;
DBCC FREESYSTEMCACHE ( 'ALL');
USE [tempdb];
DBCC SHRINKFILE (N'temp2', EMPTYFILE);
ALTER DATABASE [tempdb] REMOVE FILE [temp2];

			ALTER DATABASE tempdb MODIFY FILE (NAME=N'templog', SIZE=1048576KB , FILEGROWTH=1048576KB)
			