
DBCC DROPCLEANBUFFERS;
DBCC FREEPROCCACHE;
DBCC FREESESSIONCACHE;
DBCC FREESYSTEMCACHE ( 'ALL');
USE [tempdb];
DBCC SHRINKFILE (N'tempdb_3_20241029', EMPTYFILE);
ALTER DATABASE [tempdb]  REMOVE FILE [tempdb_3_20241029]
			
DBCC DROPCLEANBUFFERS;
DBCC FREEPROCCACHE;
DBCC FREESESSIONCACHE;
DBCC FREESYSTEMCACHE ( 'ALL');
USE [tempdb];
DBCC SHRINKFILE (N'tempdb_4_20241029', EMPTYFILE);
ALTER DATABASE [tempdb]  REMOVE FILE [tempdb_4_20241029]
			