
/* 
This query has been optimized by AI-DBA Query Optimizer (v2.4.2).
Copyright (C) 2025 AI-DBA Software Inc, all rights reserved.
Date: October 28,2025 UTC+0

{CHANGES}

*/
BEGIN TRY     CREATE  INDEX [IX_AIDBA_IX_SALESORDERDETAIL_PRODUCTID] ON [ADVENTUREWORKS].[SALES].[SALESORDERDETAIL] ([PRODUCTID],[SALESORDERID],[SALESORDERDETAILID]) INCLUDE ([CARRIERTRACKINGNUMBER],[ORDERQTY],[SPECIALOFFERID],[UNITPRICE],[UNITPRICEDISCOUNT],[ROWGUID],[MODIFIEDDATE]) WITH (DROP_EXISTING=OFF );
 END TRY BEGIN CATCH END CATCH;
