
/* 
This query has been optimized by AI-DBA Query Optimizer (v2.4.2).
Copyright (C) 2025 AI-DBA Software Inc, all rights reserved.
Date: September 06,2025 UTC+0

{CHANGES}

*/
BEGIN TRY     CREATE  INDEX [IX_AIDBA_2_20250823] ON [ADVENTUREWORKS].[SALES].[SALESORDERDETAIL] ([SALESORDERDETAILID],[SALESORDERID]) INCLUDE ([CARRIERTRACKINGNUMBER],[ORDERQTY],[PRODUCTID],[SPECIALOFFERID],[UNITPRICE],[UNITPRICEDISCOUNT],[ROWGUID],[MODIFIEDDATE]) WITH (DROP_EXISTING=ON );
 END TRY BEGIN CATCH END CATCH;
