
BEGIN TRY 

ALTER DATABASE [AdventureWorks] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[AdventureWorks] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [AdventureWorks] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[AdventureWorks] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [AdventureWorks] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[AdventureWorks] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [AdventureWorks] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[AdventureWorks] PARAMETERIZATION is SIMPLE.';
USE [AdventureWorks];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[AdventureWorks] INTERLEAVED_EXECUTION_TVF  is OFF.';
USE [AdventureWorks];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[AdventureWorks] BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [AdventureWorks] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

ALTER DATABASE [Tinashe] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[Tinashe] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [Tinashe] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[Tinashe] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [Tinashe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[Tinashe] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [Tinashe] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[Tinashe] PARAMETERIZATION is SIMPLE.';
USE [Tinashe];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = OFF;
PRINT '[Tinashe] BATCH_MODE_ON_ROWSTORE is OFF.';
USE [Tinashe];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = OFF;
PRINT '[Tinashe] DEFERRED_COMPILATION_TV  is OFF.';
USE [Tinashe];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[Tinashe] INTERLEAVED_EXECUTION_TVF  is OFF.';
USE [Tinashe];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[Tinashe] ROW_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
USE [Tinashe];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[Tinashe] BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [Tinashe] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

ALTER DATABASE [repordb2] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[repordb2] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [repordb2] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[repordb2] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [repordb2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[repordb2] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [repordb2] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[repordb2] PARAMETERIZATION is SIMPLE.';
USE [repordb2];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[repordb2] INTERLEAVED_EXECUTION_TVF  is OFF.';
USE [repordb2];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[repordb2] BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [repordb2] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

ALTER DATABASE [reportdb3] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[reportdb3] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [reportdb3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[reportdb3] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [reportdb3] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[reportdb3] PARAMETERIZATION is SIMPLE.';
USE [reportdb3];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[reportdb3] INTERLEAVED_EXECUTION_TVF  is OFF.';
USE [reportdb3];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[reportdb3] BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [reportdb3] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

ALTER DATABASE [ReportDB] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[ReportDB] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [ReportDB] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[ReportDB] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [ReportDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[ReportDB] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [ReportDB] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[ReportDB] PARAMETERIZATION is SIMPLE.';
USE [ReportDB];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[ReportDB] INTERLEAVED_EXECUTION_TVF  is OFF.';
USE [ReportDB];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[ReportDB] BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [ReportDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

ALTER DATABASE [Syazwan] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[Syazwan] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [Syazwan] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[Syazwan] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [Syazwan] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[Syazwan] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [Syazwan] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[Syazwan] PARAMETERIZATION is SIMPLE.';
USE [Syazwan];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = OFF;
PRINT '[Syazwan] BATCH_MODE_ON_ROWSTORE is OFF.';
USE [Syazwan];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = OFF;
PRINT '[Syazwan] DEFERRED_COMPILATION_TV  is OFF.';
USE [Syazwan];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[Syazwan] INTERLEAVED_EXECUTION_TVF  is OFF.';
USE [Syazwan];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[Syazwan] ROW_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
USE [Syazwan];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[Syazwan] BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [Syazwan] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

ALTER DATABASE [NaseemDB] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[NaseemDB] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [NaseemDB] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[NaseemDB] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [NaseemDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[NaseemDB] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [NaseemDB] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[NaseemDB] PARAMETERIZATION is SIMPLE.';
USE [NaseemDB];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = OFF;
PRINT '[NaseemDB] BATCH_MODE_ON_ROWSTORE is OFF.';
USE [NaseemDB];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = OFF;
PRINT '[NaseemDB] DEFERRED_COMPILATION_TV  is OFF.';
USE [NaseemDB];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[NaseemDB] INTERLEAVED_EXECUTION_TVF  is OFF.';
USE [NaseemDB];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[NaseemDB] ROW_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
USE [NaseemDB];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[NaseemDB] BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [NaseemDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

ALTER DATABASE [New_Database1] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[New_Database1] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [New_Database1] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[New_Database1] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [New_Database1] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[New_Database1] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [New_Database1] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[New_Database1] PARAMETERIZATION is SIMPLE.';
USE [New_Database1];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = OFF;
PRINT '[New_Database1] BATCH_MODE_ON_ROWSTORE is OFF.';
USE [New_Database1];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = OFF;
PRINT '[New_Database1] DEFERRED_COMPILATION_TV  is OFF.';
USE [New_Database1];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[New_Database1] INTERLEAVED_EXECUTION_TVF  is OFF.';
USE [New_Database1];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[New_Database1] ROW_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
USE [New_Database1];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[New_Database1] BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [New_Database1] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

ALTER DATABASE [umar] SET ALLOW_SNAPSHOT_ISOLATION OFF;
PRINT '[umar] SNAPSHOT ISOLATION is OFF.';
ALTER DATABASE [umar] SET READ_COMMITTED_SNAPSHOT OFF WITH NO_WAIT;
PRINT '[umar] READ_COMMITTED_SNAPSHOT is OFF.';
ALTER DATABASE [umar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF WITH NO_WAIT;
PRINT '[umar] AUTO_UPDATE_STATISTICS_ASYNC is OFF.';
ALTER DATABASE [umar] SET PARAMETERIZATION SIMPLE WITH NO_WAIT;
PRINT '[umar] PARAMETERIZATION is SIMPLE.';
USE [umar];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = OFF;
PRINT '[umar] BATCH_MODE_ON_ROWSTORE is OFF.';
USE [umar];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = OFF;
PRINT '[umar] DEFERRED_COMPILATION_TV  is OFF.';
USE [umar];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = OFF;
PRINT '[umar] INTERLEAVED_EXECUTION_TVF  is OFF.';
USE [umar];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[umar] ROW_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
USE [umar];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = OFF;
PRINT '[umar] BATCH_MODE_MEMORY_GRANT_FEEDBACK is OFF.';
END TRY 
BEGIN CATCH
	PRINT 'Database [umar] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;