
BEGIN TRY 

--CURRENT VALUE: OFF
ALTER DATABASE [AdventureWorks] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[AdventureWorks] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [AdventureWorks] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[AdventureWorks] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [AdventureWorks] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[AdventureWorks] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [AdventureWorks] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[AdventureWorks] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: OFF
USE [AdventureWorks];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[AdventureWorks] INTERLEAVED_EXECUTION_TVF  is ON.';
--CURRENT VALUE: OFF
USE [AdventureWorks];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[AdventureWorks] BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [AdventureWorks] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

--CURRENT VALUE: OFF
ALTER DATABASE [Tinashe] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[Tinashe] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [Tinashe] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[Tinashe] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [Tinashe] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[Tinashe] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [Tinashe] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[Tinashe] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: OFF
USE [Tinashe];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
PRINT '[Tinashe] BATCH_MODE_ON_ROWSTORE is ON.';
--CURRENT VALUE: OFF
USE [Tinashe];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = ON;
PRINT '[Tinashe] DEFERRED_COMPILATION_TV  is ON.';
--CURRENT VALUE: OFF
USE [Tinashe];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[Tinashe] INTERLEAVED_EXECUTION_TVF  is ON.';
--CURRENT VALUE: OFF
USE [Tinashe];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[Tinashe] ROW_MODE_MEMORY_GRANT_FEEDBACK is ON.';
--CURRENT VALUE: OFF
USE [Tinashe];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[Tinashe] BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [Tinashe] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

--CURRENT VALUE: OFF
ALTER DATABASE [repordb2] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[repordb2] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [repordb2] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[repordb2] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [repordb2] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[repordb2] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [repordb2] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[repordb2] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: OFF
USE [repordb2];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[repordb2] INTERLEAVED_EXECUTION_TVF  is ON.';
--CURRENT VALUE: OFF
USE [repordb2];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[repordb2] BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [repordb2] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

--CURRENT VALUE: OFF
ALTER DATABASE [reportdb3] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[reportdb3] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [reportdb3] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[reportdb3] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [reportdb3] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[reportdb3] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: OFF
USE [reportdb3];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[reportdb3] INTERLEAVED_EXECUTION_TVF  is ON.';
--CURRENT VALUE: OFF
USE [reportdb3];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[reportdb3] BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [reportdb3] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

--CURRENT VALUE: OFF
ALTER DATABASE [ReportDB] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[ReportDB] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [ReportDB] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[ReportDB] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [ReportDB] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[ReportDB] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [ReportDB] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[ReportDB] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: OFF
USE [ReportDB];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[ReportDB] INTERLEAVED_EXECUTION_TVF  is ON.';
--CURRENT VALUE: OFF
USE [ReportDB];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[ReportDB] BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [ReportDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

--CURRENT VALUE: OFF
ALTER DATABASE [Syazwan] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[Syazwan] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [Syazwan] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[Syazwan] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [Syazwan] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[Syazwan] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [Syazwan] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[Syazwan] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: OFF
USE [Syazwan];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
PRINT '[Syazwan] BATCH_MODE_ON_ROWSTORE is ON.';
--CURRENT VALUE: OFF
USE [Syazwan];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = ON;
PRINT '[Syazwan] DEFERRED_COMPILATION_TV  is ON.';
--CURRENT VALUE: OFF
USE [Syazwan];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[Syazwan] INTERLEAVED_EXECUTION_TVF  is ON.';
--CURRENT VALUE: OFF
USE [Syazwan];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[Syazwan] ROW_MODE_MEMORY_GRANT_FEEDBACK is ON.';
--CURRENT VALUE: OFF
USE [Syazwan];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[Syazwan] BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [Syazwan] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

--CURRENT VALUE: OFF
ALTER DATABASE [NaseemDB] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[NaseemDB] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [NaseemDB] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[NaseemDB] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [NaseemDB] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[NaseemDB] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [NaseemDB] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[NaseemDB] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: OFF
USE [NaseemDB];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
PRINT '[NaseemDB] BATCH_MODE_ON_ROWSTORE is ON.';
--CURRENT VALUE: OFF
USE [NaseemDB];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = ON;
PRINT '[NaseemDB] DEFERRED_COMPILATION_TV  is ON.';
--CURRENT VALUE: OFF
USE [NaseemDB];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[NaseemDB] INTERLEAVED_EXECUTION_TVF  is ON.';
--CURRENT VALUE: OFF
USE [NaseemDB];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[NaseemDB] ROW_MODE_MEMORY_GRANT_FEEDBACK is ON.';
--CURRENT VALUE: OFF
USE [NaseemDB];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[NaseemDB] BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [NaseemDB] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

--CURRENT VALUE: OFF
ALTER DATABASE [New_Database1] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[New_Database1] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [New_Database1] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[New_Database1] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [New_Database1] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[New_Database1] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [New_Database1] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[New_Database1] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: OFF
USE [New_Database1];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
PRINT '[New_Database1] BATCH_MODE_ON_ROWSTORE is ON.';
--CURRENT VALUE: OFF
USE [New_Database1];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = ON;
PRINT '[New_Database1] DEFERRED_COMPILATION_TV  is ON.';
--CURRENT VALUE: OFF
USE [New_Database1];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[New_Database1] INTERLEAVED_EXECUTION_TVF  is ON.';
--CURRENT VALUE: OFF
USE [New_Database1];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[New_Database1] ROW_MODE_MEMORY_GRANT_FEEDBACK is ON.';
--CURRENT VALUE: OFF
USE [New_Database1];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[New_Database1] BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [New_Database1] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;
BEGIN TRY 

--CURRENT VALUE: OFF
ALTER DATABASE [umar] SET ALLOW_SNAPSHOT_ISOLATION ON;
PRINT '[umar] SNAPSHOT ISOLATION is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [umar] SET READ_COMMITTED_SNAPSHOT ON WITH NO_WAIT;
PRINT '[umar] READ_COMMITTED_SNAPSHOT is ON.';
--CURRENT VALUE: OFF
ALTER DATABASE [umar] SET AUTO_UPDATE_STATISTICS_ASYNC ON WITH NO_WAIT;
PRINT '[umar] AUTO_UPDATE_STATISTICS_ASYNC is ON.';
--CURRENT VALUE: SIMPLE
ALTER DATABASE [umar] SET PARAMETERIZATION FORCED WITH NO_WAIT;
PRINT '[umar] PARAMETERIZATION is FORCED.';
--CURRENT VALUE: OFF
USE [umar];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_ON_ROWSTORE = ON;
PRINT '[umar] BATCH_MODE_ON_ROWSTORE is ON.';
--CURRENT VALUE: OFF
USE [umar];
ALTER DATABASE SCOPED CONFIGURATION SET DEFERRED_COMPILATION_TV  = ON;
PRINT '[umar] DEFERRED_COMPILATION_TV  is ON.';
--CURRENT VALUE: OFF
USE [umar];
ALTER DATABASE SCOPED CONFIGURATION SET INTERLEAVED_EXECUTION_TVF  = ON;
PRINT '[umar] INTERLEAVED_EXECUTION_TVF  is ON.';
--CURRENT VALUE: OFF
USE [umar];
ALTER DATABASE SCOPED CONFIGURATION SET ROW_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[umar] ROW_MODE_MEMORY_GRANT_FEEDBACK is ON.';
--CURRENT VALUE: OFF
USE [umar];
ALTER DATABASE SCOPED CONFIGURATION SET BATCH_MODE_MEMORY_GRANT_FEEDBACK = ON;
PRINT '[umar] BATCH_MODE_MEMORY_GRANT_FEEDBACK is ON.';
END TRY 
BEGIN CATCH
	PRINT 'Database [umar] is in use. During database configuration, the Database must be idle. Disconnect all users/applications/services and run this script during non-working-hour.'
END CATCH;