
/* 
This Query has been Tuned by AI-DBA Query Optimizer (v1.7.0.0).
Copyright (C) 2019-2024 AI-DBA Software Inc, all rights reserved.
Date: 12/30/2024 1:18:12 PM UTC
*/
BEGIN TRY     CREATE  INDEX [IX_AIDBA_2_20241214] ON [ADVENTUREWORKS].[SALES].[SALESORDERDETAIL] ([SALESORDERDETAILID],[SALESORDERID]) INCLUDE ([CARRIERTRACKINGNUMBER],[ORDERQTY],[PRODUCTID],[SPECIALOFFERID],[UNITPRICE],[UNITPRICEDISCOUNT],[ROWGUID],[MODIFIEDDATE]) WITH (DROP_EXISTING=ON );
 END TRY BEGIN CATCH END CATCH;
