
BEGIN TRY
	DROP INDEX [IX_AIDBA_IX_SALESORDERDETAIL_PRODUCTID]
	ON [AdventureWorks].[Sales].[SalesOrderDetail];
	PRINT 'INDEX [IX_AIDBA_IX_SALESORDERDETAIL_PRODUCTID] ON [AdventureWorks].[Sales].[SalesOrderDetail] IS DROPED.';
END TRY
BEGIN CATCH
	PRINT 'INDEX [IX_AIDBA_IX_SALESORDERDETAIL_PRODUCTID] ON [AdventureWorks].[Sales].[SalesOrderDetail] CANNOT BE DROPED.';
END CATCH;
